### ISSUE TITLE
Setting page shows error while updating 1.1.8.7 version to latest version 2.0.0

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/wp-content-copy-protection#22]
The setting page shows error while updating the 1.1.8.7 version to the latest version 2.0.0.
Sp to 
1. Upload old version that is 1.1.8.7
2. go to settings page and some "We have just taken over the development of this plugin & will be updating this page in the next release" message appear
3.  updating latest version that is 2.0.0
4.  just refresh the settings page then below error appear

https://www.screencast.com/t/EcIDjNbUHTUj

Ideally, settings page should be redirected to properly and no such error appears

**Comment by mokshasharmila13** [comment]
Not applicable

**Comment by mokshasharmila13** [comment]
Not applicable
