### ISSUE TITLE
All link on front end freeze after update latest version 2.0.0

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/wp-content-copy-protection#24]
All link on front end freeze after update latest version 2.0.0

On my site, I set the company logo and other links are Freeze. even when I click on company logo it is not redirecting to home page

https://tychesoftwares.freshdesk.com/a/tickets/10684
https://tychesoftwares.freshdesk.com/a/tickets/10675

note: All links and company logo works fine

**Comment by dhruvins** [comment]
Fixed in https://github.com/TycheSoftwares/wp-content-copy-protection/commit/d6b48f574c0b1dc7c3c8523b00ab7a57bac150c8
