### ISSUE TITLE
Removing the download button from Wordpress native player in Chrome.

### ISSUE THREAD

**Issue by kenil802** [TycheSoftwares/wp-content-copy-protection#32]
The client wants to remove the button from WordPress native player in the chrome browser.

Ticket link:  https://tychesoftwares.freshdesk.com/a/tickets/16608

**Comment by mokshasharmila13** [comment]
When we uploaded video , we have not seen any option for download button in WordPress native player 
![No download option](https://user-images.githubusercontent.com/81163257/124894088-f4fc7000-dff8-11eb-86ff-9b9084e054ae.png)

**Comment by mokshasharmila13** [comment]
When we uploaded video, we have not seen any option for a download button in WordPress native player
